
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.239.25:3306/mall?characterEncoding=utf-8&useSSL=false
  activemq:
    # activemq的broker的url
    broker-url: tcp://192.168.239.25:61616
    # 连接activemq的broker所需的账号和密码
    user: admin
    password: admin
#  自定义队列名称。这只是个常量
myqueue: pay-queue
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
wx:
  appId: #应用ID
  mchId: #直连商户号
  mchKey: #商户密钥
  notifyUrl: #回调URL
  returnUrl: #支付成功后跳转地址
alipay:
  appId: #应用ID
  privateKey: #应用私钥
  publicKey: #支付宝公钥
  notifyUrl: #回调URL
  returnUrl: #支付成功后跳转地址
server:
  port: 8082
